module.exports = [
  {
    id: 1,
    item_name: "Salary",
    amount: 5000,
    date: "2022-01-01",
    from: "ABC Company",
    category: "income",
  },
  {
    id: 2,
    item_name: "Rent",
    amount: -1000,
    date: "2022-01-02",
    from: "XYZ Property Management",
    category: "housing",
  },
  {
    id: 3,
    item_name: "Groceries",
    amount: -150,
    date: "2022-01-03",
    from: "Supermarket",
    category: "food",
  },
  {
    id: 4,
    item_name: "Electricity Bill",
    amount: -80,
    date: "2022-01-04",
    from: "Utility Company",
    category: "utilities",
  },
  {
    id: 5,
    item_name: "Gas",
    amount: -50,
    date: "2022-01-05",
    from: "Gas Station",
    category: "transportation",
  },
  {
    id: 6,
    item_name: "Birthday Gift",
    amount: -30,
    date: "2022-01-06",
    from: "Gift Shop",
    category: "gifts",
  },
  {
    id: 7,
    item_name: "Freelance Work",
    amount: 800,
    date: "2022-01-07",
    from: "Client A",
    category: "income",
  },
  {
    id: 8,
    item_name: "Phone Bill",
    amount: -60,
    date: "2022-01-08",
    from: "Mobile Carrier",
    category: "utilities",
  },
  {
    id: 9,
    item_name: "Dinner",
    amount: -40,
    date: "2022-01-09",
    from: "Restaurant",
    category: "food",
  },
  {
    id: 10,
    item_name: "Pilates",
    amount: -330,
    date: "2022-01-10",
    from: "Wick Pilates",
    category: "personal care",
  },
  {
    id: 11,
    item_name: "Freelance Work",
    amount: 500,
    date: "2022-01-11",
    from: "Client B",
    category: "income",
  },
  {
    id: 12,
    item_name: "Internet Bill",
    amount: -70,
    date: "2022-01-12",
    from: "Internet Provider",
    category: "utilities",
  },
  {
    id: 13,
    item_name: "Gas",
    amount: -30,
    date: "2022-01-13",
    from: "Gas Station",
    category: "transportation",
  },
  {
    id: 14,
    item_name: "Coffee",
    amount: -25,
    date: "2022-01-14",
    from: "Starbucks",
    category: "food",
  },
  {
    id: 15,
    item_name: "Freelance Work",
    amount: 200,
    date: "2022-01-15",
    from: "Client C",
    category: "income",
  },
];
